---
# tasks file for kostyrevaa.consul-backinator

- name: Install deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Download consul-backinator release
  unarchive:
    src:  "{{ backinator_pkg_url }}"
    dest: "{{ backinator_download_dir }}"
    remote_src: yes

- name: Move consul-backinator to installation directory
  copy:
    remote_src: yes
    mode: a+rx
    src:  "{{ backinator_download_dir }}/consul-backinator-{{ backinator_version }}-amd64-linux/consul-backinator-{{ backinator_version }}"
    dest: "{{ backinator_bin_dir }}/consul-backinator"

- name: Install consul-backinator-gs wrapper script
  when: backinator_gs_bucket is not none
  copy:
    src: consul-backinator-gs
    dest: "{{ backinator_bin_dir }}/consul-backinator-gs"
    mode: a+rx

- name: Configure consul-backinator-gs
  when: backinator_gs_bucket is not none
  copy:
    content: "GS_BUCKET={{ backinator_gs_bucket }}"
    dest: "/etc/default/consul-backinator-gs"
    mode: a+r
